services:
    todo-app:
        image: node:18-alpine
        command: sh -c "yarn install && yarn run dev"
        ports:
            - 5000:5000
        volumes:
            - ./:/app
        depends_on:
            - mysql
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
            - MYSQL_DB=todos
            - PORT=5000
        working_dir: /app
    mysql:
        image: mysql:8.0
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=todos
volumes:
    todo-mysql-data:
